sudo: required
services:
  - docker

env:
  global:
    - REPO=steadyserv/tomcat
  matrix:
    - REVISION=7.0.70 JDK=jdk7 TAG=latest

before_script:
  - env | sort
  - export VERSION=${REVISION%.*}
  - cd "$VERSION/$JDK"
  - export IMAGE="${REPO}:${VERSION}-${JDK}"

script: ../.travis/build.sh
